import { Edge, MarkerType } from "reactflow";

export const markerEndObj = {
  type: MarkerType.ArrowClosed,
  width: 10,
  height: 10,
  color: "black",
};

export const styleObj = {
  strokeWidth: 1.5,
  stroke: "black",
};

export const initialEdges = [
  {
    id: "mind_map->research",
    source: "mind_map",
    target: "research",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "mind_map->planning",
    source: "mind_map",
    target: "planning",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "mind_map->designing",
    source: "mind_map",
    target: "designing",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "mind_map->manufacturing",
    source: "mind_map",
    target: "manufacturing",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "mind_map->sales_marketing",
    source: "mind_map",
    target: "sales_marketing",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "research->external",
    source: "research",
    target: "external",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "research->internal",
    source: "research",
    target: "internal",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "planning->prd",
    source: "planning",
    target: "prd",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "planning->specs",
    source: "planning",
    target: "specs",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "designing->hardware",
    source: "designing",
    target: "hardware",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "designing->software",
    source: "designing",
    target: "software",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "manufacturing->material",
    source: "manufacturing",
    target: "material",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "manufacturing->production",
    source: "manufacturing",
    target: "production",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "sales_marketing->online",
    source: "sales_marketing",
    target: "online",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "sales_marketing->dealership",
    source: "sales_marketing",
    target: "dealership",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "external->b2c",
    source: "external",
    target: "b2c",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "external->b2b",
    source: "external",
    target: "b2b",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "b2c->online_2",
    source: "b2c",
    target: "online_2",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "b2c->interview",
    source: "b2c",
    target: "interview",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "b2c->public_data",
    source: "b2c",
    target: "public_data",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
  {
    id: "b2c->health",
    source: "b2c",
    target: "health",
    markerEnd: markerEndObj,
    style: styleObj,
    type: "smoothstep",
  },
] satisfies Edge[];
