import { Node, NodeTypes, Position } from "reactflow";
import CustomNode from "./CustomNode";

export const initialNodes = [
  {
    id: "mind_map",
    type: "input",
    position: { x: -100, y: 200 },
    sourcePosition: Position.Right,
    data: { label: "Manufacturing Process" },
    style: { backgroundColor: "black", color: "white" },
  },
  {
    id: "research",
    type: "customNode",
    position: { x: 100, y: 0 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "Research" },
  },
  {
    id: "planning",
    position: { x: 100, y: 100 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#82B3E8" },
    data: { label: "Planning" },
  },
  {
    id: "designing",
    position: { x: 100, y: 200 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#E96343" },
    data: { label: "Designing" },
  },
  {
    id: "manufacturing",
    position: { x: 100, y: 300 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#E8919D" },
    data: { label: "Manufacturing" },
  },
  {
    id: "sales_marketing",
    position: { x: 100, y: 400 },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    style: { backgroundColor: "#A684EB" },
    data: { label: "Sales Marketing" },
  },
  {
    id: "external",
    position: { x: 300, y: -25 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "External" },
  },
  {
    id: "internal",
    position: { x: 300, y: 25 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "Internal" },
  },
  {
    id: "prd",
    position: { x: 300, y: 75 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#82B3E8" },
    data: { label: "PRD" },
  },
  {
    id: "specs",
    position: { x: 300, y: 125 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#82B3E8" },
    data: { label: "Specs" },
  },
  {
    id: "hardware",
    position: { x: 300, y: 175 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#E96343" },
    data: { label: "Hardware" },
  },
  {
    id: "software",
    position: { x: 300, y: 225 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#E96343" },
    data: { label: "Software" },
  },
  {
    id: "material",
    position: { x: 300, y: 275 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#E8919D" },
    data: { label: "Material" },
  },
  {
    id: "production",
    position: { x: 300, y: 325 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#E8919D" },
    data: { label: "Production" },
  },
  {
    id: "online",
    position: { x: 300, y: 375 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#A684EB" },
    data: { label: "Online" },
  },
  {
    id: "dealership",
    position: { x: 300, y: 425 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#A684EB" },
    data: { label: "Dealership" },
  },
  {
    id: "b2c",
    position: { x: 500, y: -50 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "B2C" },
  },
  {
    id: "b2b",
    position: { x: 500, y: 0 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "B2B" },
  },
  {
    id: "online_2",
    position: { x: 700, y: -125 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "Online" },
  },
  {
    id: "interview",
    position: { x: 700, y: -75 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "Interview" },
  },
  {
    id: "public_data",
    position: { x: 700, y: -25 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "Public Data" },
  },
  {
    id: "health",
    position: { x: 700, y: 25 },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    style: { backgroundColor: "#2A4494", color: "white" },
    data: { label: "Health" },
  },
] satisfies Node[];

export const nodeTypes = {
  customNode: CustomNode,
} satisfies NodeTypes;
